### ISSUE TITLE
将来会支持移动端吗？

### ISSUE THREAD

**Issue by wxiubin** [yumemor/hexo-theme-primer#13]
disqus 国内会被墙，能否加一个button（点击加载评论），当点击了按钮再去加载disqus模块呢？
这样就不会一直在转圈。

**Comment by akarineren** [comment]
将来会支持移动端的，我也会一直使用这个主题 不过最近没有什么时间做开发  谢谢你的建议

你说的 disqus 评论 没有必要做一个按钮来加载，这样的话每一个文章都需要手动点击才能看到评论，如果没有 VPN，这样实际作用不大

**Comment by wxiubin** [comment]
当天就能回复，你真勤奋啊~
