### ISSUE TITLE
Link not working.

### ISSUE THREAD

**Issue by amandeepmittal** [yumemor/hexo-theme-primer#15]
Hi,

link: [http://yumemor.github.io/](http://yumemor.github.io/) is not working. Any update where I can see a demo ?

**Comment by akarineren** [comment]
Sorry now that there is no update to this item, I try to find someone who is using the subject to give you a demo but did not find you if the interest can try clone local view

maybe http://justpsvm.com/hexo-theme-primer/#/

**Comment by amandeepmittal** [comment]
Will try to clone a local view. Thanks!
