### ISSUE TITLE
发现主题的分页和文章title俩bug

### ISSUE THREAD

**Issue by 0xhhhhh** [yumemor/hexo-theme-primer#6]
分页这个还好，不是什么大问题
![page](https://cloud.githubusercontent.com/assets/16428340/20951286/dd9961be-bc5f-11e6-8b11-f5cf2a15a0bc.png)
但是文章title不显示是否会不利于SEO收录呢？
![title](https://cloud.githubusercontent.com/assets/16428340/20951285/dd95c75c-bc5f-11e6-82b2-e3397d870af4.png)

昨天折腾到半夜，才调好，这俩bug让我感觉特别不适应，还有就是多说评论全没了，不知道为何

**Comment by Bakumon** [comment]
title 怎么搞好的，求分享

**Comment by 0xhhhhh** [comment]
@Bakumon 我的Title并没有搞好啊，所以才过来提问，看看作者是如何考虑这方面的

**Comment by 0xhhhhh** [comment]
我的atom.xml不知为何是这种呢
![qq 20161207100629](https://cloud.githubusercontent.com/assets/16428340/20952091/dd9c10b2-bc64-11e6-838c-6a6100c3550e.png)

**Comment by akarineren** [comment]
分页和文章标题的问题已经 push 上来了，针对文章这一块的 SEO 确实没有注意 后面我准备添加一些新的标签来更好的支持 SEO。

另外，你的 atom.xml 应该是插件引起的 和主题无关 ，你可以去 hexo.io 插件区域里面找找答案。

**Comment by 0xhhhhh** [comment]
是否会添加Google统计呢？

**Comment by akarineren** [comment]
像这种第三方的统计插件 比如 百度 gogole 文章访问量 在后面的升级中我会添加进入 ，不过你现在也完全可以自己添加 非常简单。

**Comment by akarineren** [comment]
多说评论没有的话 检查你的多说用户名开始的时候是不是没有修改默认 是后面修改的 更改了用户名 之前的评论当然就没有了
