### ISSUE TITLE
本地搜索的问题

### ISSUE THREAD

**Issue by isnine** [yumemor/hexo-theme-primer#7]
更新了新主题，也安装了插件，改了两个_config.yml文件，但是本地搜索好像还是和之前谷歌搜索一样

**Comment by 0xhhhhh** [comment]
我的本地搜索没什么作用，然后就换Google搜索了。

**Comment by Bakumon** [comment]
安装 Search 插件了吗

**Comment by Bakumon** [comment]
![image](https://cloud.githubusercontent.com/assets/12182189/20952284/4137c2be-bc66-11e6-8075-c6b1223251c1.png)

效果是这样的，输入的同时就查找了，不需要回车

**Comment by 0xhhhhh** [comment]
@Bakumon 回去我再看看

**Comment by Bakumon** [comment]
我拉主题代码新建 hexo 目录重新测试了下，也是 ok 的，不知道你们问题在哪

**Comment by akarineren** [comment]
搜索添加键盘支持 @anshengme  你可以重新更新下来 ，修改搜索方式之后 建议先 hexo clean 在上传到博客。
